import { $ , runtimeState } from './runtime.js';

const STORE_KEY = 'ui-preferences';

const translations = {
  en: {
    'header.workspace': 'Live Workspace',
    'views.dashboard': 'Dashboard',
    'views.tests': 'Essais',
    'views.method': 'Method',
    'views.sequencer': 'Sequence',
    'views.workflow': 'Workflow',
    'views.settings': 'Settings',
    'footer.systemReady': 'SYSTEM READY',
    'footer.simulatorReady': 'SIMULATOR READY',
    'footer.connectionDegraded': 'CHECK CONNECTIONS',
    'footer.waitingForConnection': 'WAITING FOR CONNECTION',
    'footer.latency': 'Latency',
    'footer.build': 'Build',
    'sidebar.productSubtitle': 'Industrial ultrasonic control console',
    'sidebar.nav.dashboard': 'Dashboard',
    'sidebar.nav.tests': 'Essais',
    'sidebar.nav.method': 'Method',
    'sidebar.nav.settings': 'Settings',
    'sidebar.simulation.title': 'Operating Mode',
    'sidebar.simulation.description': 'Choose the target mode, then click Start or Stop.',
    'sidebar.simulation.hardware': 'Hardware',
    'sidebar.simulation.simulation': 'Simulation',
    'sidebar.simulation.start': 'Start',
    'sidebar.simulation.stop': 'Stop',
    'dashboard.realtime.title': 'Real-Time Data',
    'dashboard.realtime.description': 'Current live readings from the DCX stack.',
    'dashboard.labels.frequency': 'Frequency',
    'dashboard.labels.amplitude': 'Amplitude',
    'dashboard.labels.cycles': 'Cycles',
    'dashboard.indicators.ready': 'Ready',
    'dashboard.indicators.sonics': 'Sonics',
    'dashboard.indicators.alarm': 'Alarm',
    'dashboard.indicators.seeking': 'Seeking',
    'dashboard.manual.title': 'Manual Control',
    'dashboard.manual.description': 'Direct operator commands for start, stop, tune, and reset.',
    'dashboard.manual.amplitudeTarget': 'Amplitude Target (%)',
    'dashboard.manual.start': 'Start',
    'dashboard.manual.stop': 'Stop',
    'dashboard.manual.seek': 'Seek',
    'dashboard.manual.reset': 'Reset',
    'dashboard.graph.title': 'Telemetry Graph',
    'dashboard.graph.description': 'Plots live telemetry whenever the controller is online, including idle periods.',
    'dashboard.graph.xAxis': 'X-Axis',
    'dashboard.graph.yAxis': 'Y-Axis',
    'dashboard.graph.play': 'Play',
    'dashboard.graph.pause': 'Pause',
    'dashboard.graph.clear': 'Clear',
    'chart.axis.time': 'Time',
    'chart.axis.frequency': 'Frequency',
    'chart.axis.amplitude': 'Amplitude',
    'chart.axis.power': 'Power',
    'chart.axis.cycles': 'Cycles',
    'sequencer.library.title': 'Sequence Library',
    'sequencer.library.description': 'Saved routines can be reviewed and loaded here.',
    'sequencer.library.empty': 'Saved sequences will appear here.',
    'sequencer.sequenceName': 'Sequence Name',
    'sequencer.buttons.saveChanges': 'Save Changes',
    'sequencer.buttons.saveSequence': 'Save Sequence',
    'sequencer.buttons.createSequence': 'Create Sequence',
    'sequencer.buttons.execute': 'Execute Sequence',
    'sequencer.buttons.stop': 'Stop Sequence',
    'sequencer.buttons.wipeAll': 'Wipe All',
    'sequencer.blocks.pulse': 'Pulse',
    'sequencer.blocks.pause': 'Stop',
    'sequencer.construction.title': 'Sequence Construction',
    'sequencer.construction.description': 'Arrange pulse and stop blocks, then execute the timeline.',
    'sequencer.timeline.label': 'Timeline (drag blocks to reorder)',
    'sequencer.config.title': 'Active Routine Config',
    'sequencer.config.description': 'Global settings that shape the current timeline execution.',
    'sequencer.config.globalRamp': 'Global Ramp (ms)',
    'sequencer.config.autoAbort': 'Auto-Abort',
    'sequencer.config.loopCount': 'Loop Count',
    'sequencer.config.onAlarm': 'On Alarm',
    'sequencer.config.never': 'Never',
    'sequencer.actions.load': 'Load',
    'sequencer.actions.duplicate': 'Duplicate',
    'sequencer.actions.delete': 'Delete',
    'sequencer.blocks.single': 'block',
    'sequencer.blocks.plural': 'blocks',
    'sequencer.confirmDelete': 'Delete saved sequence "{name}"?',
    'sequencer.saveState.draft': 'New draft not saved',
    'sequencer.saveState.dirty': 'Unsaved changes',
    'sequencer.saveState.savingNew': 'Saving new sequence...',
    'sequencer.saveState.savingChanges': 'Saving changes...',
    'sequencer.saveState.saved': 'All changes saved',
    'sequencer.saveState.nameRequired': 'Enter a sequence name before saving',
    'sequencer.saveState.duplicateName': 'A sequence with this name already exists',
    'sequencer.saveState.empty': 'Add at least one block before saving',
    'sequencer.saveState.loadBeforeSave': 'Load a saved sequence before using Save Changes',
    'sequencer.saveState.autoSaveFailed': 'Auto-save failed',
    'sequencer.copySuffix': 'Copy',
    'sequencer.progress.idle': 'IDLE',
    'workflow.title': 'Advanced Scripting Workflow',
    'workflow.description': 'Validate and run higher-level command scripts against the controller.',
    'workflow.placeholder': '// Example:\nSET_AMP 80\nWAIT 1000\nSTART\nWAIT 5000\nSTOP',
    'workflow.library.title': 'Workflow Library',
    'workflow.library.description': 'Save reusable workflow scripts for repeated operator tasks.',
    'workflow.library.name': 'Workflow Name',
    'workflow.library.namePlaceholder': 'Inspection Routine...',
    'workflow.library.save': 'Save to Library',
    'workflow.library.load': 'Load',
    'workflow.library.delete': 'Delete',
    'workflow.library.empty': 'Saved workflows will appear here.',
    'workflow.library.ready': 'Library ready',
    'workflow.library.saved': 'Workflow saved to library',
    'workflow.library.updated': 'Workflow updated in library',
    'workflow.library.loaded': 'Workflow loaded from library',
    'workflow.library.deleted': 'Workflow removed from library',
    'workflow.library.exampleLoaded': 'Example loaded into editor',
    'workflow.library.errorLoad': 'Could not load saved workflows',
    'workflow.library.errorNameRequired': 'Enter a workflow name before saving',
    'workflow.library.errorScriptRequired': 'Enter a workflow script before saving',
    'workflow.library.errorDuplicate': 'A workflow with this name already exists',
    'workflow.library.confirmDelete': 'Delete saved workflow "{name}"?',
    'workflow.library.lineSingle': 'line',
    'workflow.library.linePlural': 'lines',
    'workflow.help.title': 'Syntax Help & Examples',
    'workflow.help.description': 'Use these supported commands and starter examples to build a valid workflow script.',
    'workflow.help.commands': 'Supported Commands',
    'workflow.help.start': 'Start sonics, optional amplitude override.',
    'workflow.help.stop': 'Stop sonics immediately.',
    'workflow.help.setAmp': 'Set the weld amplitude target.',
    'workflow.help.wait': 'Pause execution for a duration in milliseconds.',
    'workflow.help.seek': 'Run a seek cycle.',
    'workflow.help.reset': 'Clear active alarms.',
    'workflow.help.examples': 'Example Scripts',
    'workflow.example.ramp': 'Ramp Check',
    'workflow.example.seek': 'Seek Check',
    'workflow.example.pulse': 'Pulse Train',
    'tests.title': 'Available Essais',
    'tests.description': 'Filter saved sequence and workflow essais, then load one for comparison.',
    'tests.filters.search': 'Search',
    'tests.filters.searchPlaceholder': 'Search essais...',
    'tests.filters.sort': 'Sort By',
    'tests.filters.sort.date': 'Date',
    'tests.filters.sort.name': 'Name',
    'tests.filters.sort.blocks': 'Blocks',
    'tests.filters.updatedAt': 'Updated',
    'tests.list.title': 'Matching Essais',
    'tests.list.empty': 'No saved essais found.',
    'tests.actions.load': 'Load Essai',
    'tests.actions.run': 'Run',
    'tests.type.sequence': 'Sequence',
    'tests.type.workflow': 'Workflow',
    'tests.graph.title': 'Essai Comparison Graph',
    'tests.graph.description': 'Load a saved essai to plot its ideal profile, then run it to overlay measured or simulated data.',
    'tests.graph.loaded': 'Loaded Essai',
    'tests.graph.noneLoaded': 'No essai loaded',
    'tests.graph.noneLoadedDescription': 'Load a saved sequence or workflow essai to compare ideal and actual traces.',
    'tests.graph.runLoaded': 'Run Loaded Essai',
    'tests.graph.ideal': 'Ideal',
    'tests.graph.measured': 'Measured',
    'tests.graph.simulated': 'Simulated',
    'tests.sequences.title': 'Sequence Essais',
    'tests.sequences.description': 'Browse saved sequence essais and load one into Method.',
    'tests.workflows.title': 'Workflow Essais',
    'tests.workflows.description': 'Browse saved workflow essais and load one into Method.',
    'method.title': 'Method Builder',
    'method.description': 'Create and run sequence or workflow methods from one workspace.',
    'method.home.new': 'Create New',
    'method.home.blank': 'Blank',
    'method.home.example': 'Example',
    'method.home.exampleDescription': 'Start from a tested script pattern.',
    'method.home.newSequence': 'New Sequence',
    'method.home.newSequenceDescription': 'Start with an empty pulse timeline.',
    'method.home.newWorkflow': 'New Workflow',
    'method.home.newWorkflowDescription': 'Open a clean scripting workspace.',
    'method.home.recents': 'Recents',
    'method.home.all': 'All',
    'method.home.favorites': 'Favorites',
    'method.home.sequence': 'Sequence',
    'method.home.workflow': 'Workflow',
    'method.home.searchPlaceholder': 'Search methods',
    'method.home.empty': 'No methods match this view yet.',
    'method.home.favorite': 'Favorite',
    'method.home.unfavorite': 'Favorited',
    'method.home.duplicate': 'Duplicate',
    'method.home.delete': 'Delete',
    'method.home.updated': 'Updated',
    'method.navigation.home': 'Method Home',
    'method.sequence.title': 'Sequence Method',
    'method.sequence.description': 'Name, save, and prepare a sequence-based essai method.',
    'method.workflow.title': 'Workflow Method',
    'method.workflow.description': 'Save, load files, and execute a workflow-based essai method.',
    'sequencer.editor.title': 'Sequence Builder',
    'sequencer.editor.description': 'Build, save, and run sequence methods from a focused editor.',
    'sequencer.preview.title': 'Sequence Preview',
    'sequencer.preview.description': 'Visualize the planned amplitude profile before running the sequence.',
    'sequencer.preview.dataset': 'Sequence Preview',
    'sequencer.preview.loopSingle': 'loop',
    'sequencer.preview.loopPlural': 'loops',
    'workflow.editor.title': 'Workflow Builder',
    'workflow.editor.description': 'Write, validate, and save workflow methods from a focused editor.',
    'workflow.statusLabel': 'Workflow Status',
    'workflow.status.idle': 'IDLE',
    'workflow.status.preparing': 'PREPARING',
    'workflow.status.stopping': 'STOPPING',
    'workflow.status.completed': 'COMPLETED',
    'workflow.status.stopped': 'STOPPED',
    'workflow.status.error': 'ERROR',
    'workflow.status.line': 'LINE {current}/{total} · {command}',
    'workflow.file.none': 'No script loaded',
    'workflow.file.loaded': 'Loaded: {name}',
    'workflow.run': 'Validate & Execute',
    'workflow.stop': 'Stop Workflow',
    'workflow.load': 'Load Script...',
    'workflow.save': 'Save Script...',
    'settings.connection.title': 'Connection Parameters',
    'settings.connection.description': 'Choose the transport layer and initialize or release the device.',
    'settings.interfaceMode': 'Interface Mode',
    'settings.interface.http': 'Direct HTTP (Branson DCX)',
    'settings.interface.serial': 'Teensy 4.1 Serial Bridge',
    'settings.targetIp': 'Target IP Address',
    'settings.communicationPort': 'Communication Port',
    'settings.description': 'Organize system preferences, I/O routing and monitoring, signature plots, alarm history, and documentation in one workspace.',
    'settings.tabs.system': 'System',
    'settings.tabs.setup': 'Setup',
    'settings.tabs.io': 'I/O Configuration',
    'settings.tabs.signature': 'Seek & Horn Signature',
    'settings.tabs.alarms': 'Alarm Log',
    'settings.tabs.docs': 'Help & Docs',
    'settings.setup.title': 'Generator Setup',
    'settings.setup.description': 'Adjust amplitude, frequency, seek, and power-on defaults from one setup workspace.',
    'settings.setup.sections.amplitude': 'Amplitude',
    'settings.setup.sections.frequency': 'Frequency',
    'settings.setup.sections.misc': 'MISC SETUP',
    'settings.setup.sections.seek': 'SEEK',
    'settings.setup.sections.powerOn': 'POWER ON',
    'settings.setup.amplitudeRamp': 'Amplitude Ramp (ms)',
    'settings.setup.external': 'External',
    'settings.setup.digitalTune': 'Digital Tune (Hz)',
    'settings.setup.internalOffset': 'Internal Offset (Hz)',
    'settings.setup.externalOffset': 'External Offset',
    'settings.setup.endOfWeldStore': 'End of Weld Store',
    'settings.setup.clearMemoryWithReset': 'Clear memory with Reset',
    'settings.setup.clearMemoryBeforeSeek': 'Clear memory before Seek',
    'settings.setup.setWithHornScan': 'Set with Horn Scan',
    'settings.setup.alarmsResetRequired': 'Alarms - Reset Required',
    'settings.setup.seekRamp': 'Seek Ramp (ms)',
    'settings.setup.seekTime': 'Seek Time (ms)',
    'settings.setup.frequencyOffset': 'Frequency Offset (Hz)',
    'settings.setup.timedSeek': 'Timed Seek',
    'settings.setup.off': 'Off',
    'settings.setup.seek': 'Seek',
    'settings.setup.scan': 'Scan',
    'settings.setup.clearMemory': 'Clear Memory',
    'settings.setup.rangeIndicator': 'Range: {min} to {max}',
    'settings.setup.save': 'Save',
    'settings.setup.cancel': 'Cancel',
    'settings.setup.restoreDefaults': 'Restore to Defaults',
    'settings.preferences.title': 'Preferences',
    'settings.preferences.description': 'Choose the application language and visual theme.',
    'settings.system.title': 'System Maintenance',
    'settings.system.description': 'Run operator-side maintenance actions for the connected controller.',
    'settings.systemInfo.title': 'System Information',
    'settings.systemInfo.description': 'Review controller and power-supply identification details at a glance.',
    'settings.systemInfo.systemPanel': 'System',
    'settings.systemInfo.powerSupplyPanel': 'Power Supply',
    'settings.systemInfo.system': 'System',
    'settings.systemInfo.display': 'Display',
    'settings.systemInfo.softwareVersion': 'Software Version',
    'settings.systemInfo.systemVersion': 'System Version',
    'settings.systemInfo.fpgaVersion': 'FPGA Version',
    'settings.systemInfo.dcxCrc': 'DCX CRC',
    'settings.systemInfo.systemCrc': 'System CRC',
    'settings.systemInfo.powerLevel': 'Power Level',
    'settings.systemInfo.frequency': 'Frequency',
    'settings.systemInfo.serialNumber': 'Serial Number',
    'settings.systemInfo.lifetimeCycles': 'Lifetime Cycles',
    'settings.systemInfo.generalAlarms': 'General Alarms',
    'settings.systemInfo.hoursOfSonics': 'Hours of Sonics',
    'settings.systemInfo.powerOnHours': 'Power-On Hours',
    'settings.systemInfo.specPassword': 'Spec Password',
    'settings.systemInfo.specPasswordEnabled': 'Spec Password Enabled',
    'settings.docs.title': 'Help & Documentation',
    'settings.docs.description': 'Structured operating reference for connection, control, methods, and commissioning limits.',
    'settings.docs.referenceEyebrow': 'Operator Reference',
    'settings.docs.referenceTitle': 'DCX / Teensy Operating Reference',
    'settings.docs.referenceBody': 'Use this controlled reference for daily operation, commissioning checks, and training.',
    'settings.docs.meta.docType': 'Document Type',
    'settings.docs.meta.docTypeValue': 'Operator Guide',
    'settings.docs.meta.controlPolicy': 'Control Policy',
    'settings.docs.meta.controlPolicyValue': 'Sonics routed through Teensy',
    'settings.docs.meta.hardwareMode': 'Hardware Mode',
    'settings.docs.meta.hardwareModeValue': 'Branson HTTP + Teensy Serial',
    'settings.docs.meta.simulationMode': 'Simulation Mode',
    'settings.docs.meta.simulationModeValue': 'Internal software model',
    'settings.docs.notice.title': 'Safety & Routing Notice',
    'settings.docs.notice.description': 'Review these control-path rules before operating hardware.',
    'settings.docs.notice.hardwareTitle': 'Hardware Mode',
    'settings.docs.notice.hardwareBody': 'Hardware mode initializes the Branson controller and the Teensy interface together before operation.',
    'settings.docs.notice.sonicsTitle': 'Sonics Control',
    'settings.docs.notice.sonicsBody': 'Start and Stop sonics are intentionally issued only through Teensy commands START and STOP.',
    'settings.docs.notice.bransonTitle': 'Branson Functions',
    'settings.docs.notice.bransonBody': 'Status readback, seek, reset, and parameter writes remain on the Branson HTTP control path.',
    'settings.docs.start.title': 'Standard Operating Procedure',
    'settings.docs.start.description': 'Follow this standard procedure before any manual or automated run.',
    'settings.docs.start.connectTitle': 'Connect',
    'settings.docs.start.connectBody': 'Select Hardware or Simulation. In Hardware mode the app connects to the Branson controller and the Teensy interface before operation.',
    'settings.docs.start.statusTitle': 'Check Status',
    'settings.docs.start.statusBody': 'Open the Dashboard to confirm live values, indicators, and connection state before running anything.',
    'settings.docs.start.manualTitle': 'Run Manually',
    'settings.docs.start.manualBody': 'Use Start, Stop, Seek, Reset, and the amplitude target for quick manual control.',
    'settings.docs.start.methodsTitle': 'Use Methods',
    'settings.docs.start.methodsBody': 'Move to Sequence or Workflow when you want repeatable test routines instead of one-off manual actions.',
    'settings.docs.manual.title': 'Manual Controls',
    'settings.docs.manual.description': 'These are the fastest controls for direct operator actions.',
    'settings.docs.manual.amplitudeTitle': 'Amplitude Target',
    'settings.docs.manual.amplitudeBody': 'Set the amplitude target before pressing Start so the next weld begins with the expected output level.',
    'settings.docs.manual.startStopTitle': 'Start / Stop',
    'settings.docs.manual.startStopBody': 'Use Start and Stop only in Hardware mode. The app sends START and STOP to the Teensy interface.',
    'settings.docs.manual.seekTitle': 'Seek',
    'settings.docs.manual.seekBody': 'Use Seek to run a tuning cycle or begin a horn signature scan.',
    'settings.docs.manual.resetTitle': 'Reset',
    'settings.docs.manual.resetBody': 'Use Reset after an alarm or overload condition to clear the controller state before running again.',
    'settings.docs.signature.title': 'Signature Acquisition Reference',
    'settings.docs.signature.description': 'Select the appropriate acquisition mode, review the captured traces, and export the data set when required.',
    'settings.docs.signature.weldTitle': 'Weld Data Graph',
    'settings.docs.signature.weldBody': 'Use this mode to capture 5 seconds of weld data, choose the traces you want to display, and export the result when needed.',
    'settings.docs.signature.hornTitle': 'Horn Signature Graph',
    'settings.docs.signature.hornBody': 'Use this mode during seek to compare horn resonance behavior and export the scan after it completes.',
    'settings.docs.methods.title': 'Sequences & Workflows',
    'settings.docs.methods.description': 'Use these tools when you need repeatable multi-step runs instead of quick manual actions.',
    'settings.docs.methods.sequenceTitle': 'Sequence',
    'settings.docs.methods.sequenceBody': 'Use the Sequence view to build timed pulse and pause blocks with configurable amplitudes and ramps.',
    'settings.docs.methods.workflowTitle': 'Workflow',
    'settings.docs.methods.workflowBody': 'Use the Workflow view for step-by-step procedures that combine start, stop, seek, reset, waits, and amplitude changes.',
    'settings.docs.methods.reviewTitle': 'Review',
    'settings.docs.methods.reviewBody': 'Use Alarm Log and System Output in Settings to review what happened during a run.',
    'settings.docs.limits.title': 'Known Limits & Commissioning Notes',
    'settings.docs.limits.description': 'These notes help explain why a feature may appear in the UI but not behave fully yet.',
    'settings.docs.limits.clearMemory': 'The memory wipe button is visible but not available yet.',
    'settings.docs.limits.systemMetadata': 'System information depends on controller firmware; blank fields mean the device did not report a value.',
    'settings.docs.limits.advancedTelemetry': 'Some advanced signature traces may stay empty until the controller provides those measurements.',
    'settings.docs.columns.function': 'Function',
    'settings.docs.columns.mapping': 'Mapping',
    'settings.docs.columns.usedBy': 'Used By',
    'settings.docs.columns.command': 'Command',
    'settings.docs.columns.detail': 'Detail',
    'settings.docs.transports.title': 'Transport Architecture',
    'settings.docs.transports.description': 'Hardware mode combines Branson HTTP control with Teensy-managed sonics commands; simulation keeps the UI live without hardware.',
    'settings.docs.transports.httpTitle': 'Branson HTTP',
    'settings.docs.transports.httpBody': 'Handles status readback, seek, reset, and parameter writes through Branson function/cmd endpoints.',
    'settings.docs.transports.serialTitle': 'Teensy Serial',
    'settings.docs.transports.serialBody': 'Handles sonics enable commands in hardware mode by sending START and STOP to the Teensy.',
    'settings.docs.transports.simTitle': 'Simulation',
    'settings.docs.transports.simBody': 'Simulates telemetry and state changes for safe UI validation without live hardware.',
    'settings.docs.workflow.title': 'Workflow Command Reference',
    'settings.docs.workflow.description': 'These workflow and sequence operations are already translated into controller actions.',
    'settings.docs.workflow.start': 'Start sonics with optional amplitude input.',
    'settings.docs.workflow.stop': 'Stop sonics immediately.',
    'settings.docs.workflow.setAmp': 'Update weld amplitude before the next weld.',
    'settings.docs.workflow.seek': 'Run a seek cycle / horn scan.',
    'settings.docs.workflow.reset': 'Clear active alarms.',
    'settings.docs.workflow.wait': 'Pause for a duration in milliseconds.',
    'settings.docs.functions.title': 'Control Interface Mapping',
    'settings.docs.functions.description': 'These control actions are already reachable through the current UI, sequence engine, or workflow engine.',
    'settings.docs.functions.statusRead': 'Status Read',
    'settings.docs.functions.startSonics': 'Start Sonics',
    'settings.docs.functions.stopSonics': 'Stop Sonics',
    'settings.docs.functions.seek': 'Seek',
    'settings.docs.functions.alarmReset': 'Alarm Reset',
    'settings.docs.functions.setAmplitude': 'Set Amplitude',
    'settings.docs.usage.statusRead': 'Heartbeat, dashboard, diagnostics',
    'settings.docs.usage.startSonics': 'Dashboard start, sequences, workflows',
    'settings.docs.usage.stopSonics': 'Dashboard stop, sequences, workflows',
    'settings.docs.usage.seek': 'Dashboard seek, horn signature, workflows',
    'settings.docs.usage.alarmReset': 'Dashboard reset, overload reset, workflows',
    'settings.docs.usage.setAmplitude': 'Manual start target, sequences, workflows',
    'settings.docs.mapping.statusRead': 'Reads live controller state, telemetry, and available metadata.',
    'settings.docs.mapping.startSonics': 'Applies amplitude target on Branson first, then issues START to Teensy.',
    'settings.docs.mapping.stopSonics': 'Issues STOP to Teensy to end sonics in hardware mode.',
    'settings.docs.mapping.seek': 'Runs the controller-managed seek cycle from the Branson interface.',
    'settings.docs.mapping.alarmReset': 'Clears controller alarms and overload state through the Branson interface.',
    'settings.docs.mapping.setAmplitude': 'Writes amplitude parameters to Branson before the next weld or scripted step.',
    'settings.docs.parameters.title': 'Supported Parameter Writes',
    'settings.docs.parameters.description': 'These controller parameter keys are already accepted by the parameter update path.',
    'settings.docs.gaps.title': 'Known Gaps',
    'settings.docs.gaps.description': 'These areas still need controller-side or app-side implementation work.',
    'settings.docs.gaps.clearMemory': 'CLR / memory wipe command',
    'settings.docs.gaps.systemMetadata': 'System metadata readback (LCD version, CRCs, serial number)',
    'settings.docs.gaps.advancedTelemetry': 'Live phase/current/PWM amplitude telemetry from controller',
    'settings.io.title': 'I/O Configuration',
    'settings.io.description': 'Keep routing controls and live digital and analog I/O in one view.',
    'settings.io.digitalInputs': 'Digital Inputs',
    'settings.io.digitalOutputs': 'Digital Outputs',
    'settings.io.analogInputs': 'Analog Inputs',
    'settings.io.analogOutputs': 'Analog Outputs',
    'settings.io.externalStart': 'External Start',
    'settings.io.externalSeek': 'External Seek',
    'settings.io.externalReset': 'External Reset',
    'settings.io.memoryClear': 'Memory Clear',
    'settings.io.ready': 'Ready',
    'settings.io.sonicsActive': 'SonicsActive',
    'settings.io.generalAlarm': 'GeneralAlarm',
    'settings.io.seekScanOut': 'Seek/Scan Out',
    'settings.io.amplitudeIn': 'Amplitude In (V)',
    'settings.io.frequencyOffset': 'Frequency Offset (V)',
    'settings.io.powerOut': 'Power Out (V)',
    'settings.io.amplitudeOut': 'Amplitude Out (V)',
    'settings.language': 'Language',
    'settings.language.english': 'English',
    'settings.language.french': 'French',
    'settings.theme': 'Theme Mode',
    'settings.theme.dark': 'Dark',
    'settings.theme.light': 'Light',
    'settings.theme.system': 'System',
    'settings.routing.title': 'Control Routing',
    'settings.routing.description': 'Delegate each command family to Ethernet, serial, or the main mode.',
    'settings.routing.followMainMode': 'Follow Main Mode',
    'settings.routing.ethernet': 'Ethernet (DCX)',
    'settings.routing.serial': 'Teensy (Serial)',
    'settings.routing.sonics': 'Sonics (Start/Stop)',
    'settings.routing.amplitude': 'Amplitude Control',
    'settings.routing.seek': 'Seek / Tune',
    'settings.routing.reset': 'Alarm Reset',
    'settings.signature.title': 'Seek & Horn Signature Graph',
    'settings.signature.description': 'Switch between loading the stored weld graph and running a horn signature scan in one workspace.',
    'settings.signature.clear': 'Clear Graph',
    'settings.signature.weldDataGraph': 'Weld Data Graph',
    'settings.signature.hornSignatureGraph': 'Horn Signature Graph',
    'settings.signature.weldDataDescription': 'Load the stored weld graph from the DCX over Ethernet and view or export the selected parameters.',
    'settings.signature.hornSignatureDescription': 'Diagnose horn resonance with phase, current, and amplitude scan traces you can view or export.',
    'settings.signature.startWeldCapture': 'Load Weld Graph',
    'settings.signature.startHornScan': 'Start Horn Scan',
    'settings.signature.startTest': 'Start Test',
    'settings.signature.resetOverload': 'Reset Overload',
    'settings.signature.abortHornScan': 'Abort Horn Scan',
    'settings.signature.status': 'Status',
    'settings.signature.result': 'Result',
    'settings.signature.passed': 'Passed',
    'settings.signature.failed': 'Failed',
    'settings.signature.aborted': 'Aborted',
    'settings.signature.scanIdle': 'Idle',
    'settings.signature.scanRunning': 'Horn scan in progress',
    'settings.signature.scanAborting': 'Aborting horn scan',
    'settings.signature.scanPassed': 'Horn scan complete',
    'settings.signature.scanFailed': 'Horn scan failed',
    'settings.signature.scanAborted': 'Horn scan aborted',
    'settings.signature.run': 'Run',
    'settings.signature.frequency': 'Frequency',
    'settings.signature.memory': 'Memory',
    'settings.signature.amplitude': 'Amplitude',
    'settings.signature.power': 'Power',
    'settings.signature.seek': 'Seek',
    'settings.signature.phase': 'Phase',
    'settings.signature.current': 'Current',
    'settings.signature.pwmAmplitude': 'PWM Amplitude',
    'settings.signature.alarm': 'Alarm',
    'settings.signature.okStored': 'OK-Memory Stored',
    'settings.signature.overloadCleared': 'Overload-Cleared',
    'settings.signature.updateGraph': 'Update Graph',
    'settings.signature.exportGraph': 'Export Graph Data',
    'settings.signature.drawFrom': 'Draw From (ms)',
    'settings.signature.drawFromHz': 'Draw From (Hz)',
    'settings.signature.drawTo': 'To (ms)',
    'settings.signature.drawToHz': 'To (Hz)',
    'settings.signature.graphSelection': 'Graph Selection',
    'settings.signature.xValue': 'X Value',
    'settings.signature.xValueFrequency': 'Frequency (Hz)',
    'settings.signature.yValue': 'Y Value',
    'settings.signature.setDefault': 'Set Default',
    'settings.signature.updateValue': 'Update Value',
    'settings.signature.percentScale': 'Amplitude / Power (%)',
    'settings.signature.amplitudeScale': 'Amplitude (%)',
    'settings.signature.phaseScale': 'Phase (deg)',
    'settings.signature.currentScale': 'Current',
    'settings.signature.seekActive': 'ACTIVE',
    'settings.signature.seekIdle': 'IDLE',
    'settings.signature.dataset.frequency': 'Frequency',
    'settings.signature.dataset.power': 'Power',
    'settings.signature.dataset.amplitude': 'Amplitude',
    'settings.signature.dataset.phase': 'Phase',
    'settings.signature.dataset.current': 'Current',
    'settings.signature.dataset.pwmAmplitude': 'PWM Amplitude',
    'settings.signature.weldGraphSetup': 'Weld Graph Setup',
    'settings.signature.weldPresetData': 'Weld Preset Data',
    'settings.signature.loadedPresetValues': 'Loaded preset values',
    'settings.signature.noPresetData': 'No preset data loaded.',
    'settings.signature.scanSetup': 'Horn Scan Setup',
    'settings.signature.resonance': 'Resonance',
    'settings.signature.frequencyStart': 'Frequency Start (Hz)',
    'settings.signature.frequencyStop': 'Frequency Stop (Hz)',
    'settings.signature.frequencyStep': 'Frequency Step (Hz)',
    'settings.signature.stepDelay': 'Step Delay (ms)',
    'settings.signature.scanAmplitude': 'Amplitude (%)',
    'settings.signature.scanCurrent': 'Current (%)',
    'settings.signature.seriesResonantPoint1': 'Series Resonant Point 1 (Hz)',
    'settings.signature.parallelResonantPoint1': 'Parallel Resonant Point 1 (Hz)',
    'settings.alarms.title': 'Alarm Log',
    'settings.alarms.description': 'Track alarm transitions detected from live telemetry.',
    'settings.alarms.time': 'Time',
    'settings.alarms.state': 'State',
    'settings.alarms.detail': 'Detail',
    'settings.alarms.empty': 'No alarm events recorded yet.',
    'settings.alarms.active': 'ACTIVE',
    'settings.alarms.cleared': 'CLEAR',
    'settings.output.title': 'System Output',
    'settings.output.description': 'Review raw operator and controller output entries.',
    'settings.diagnostics.title': 'Diagnostics & Logs',
    'settings.diagnostics.description': 'Watch controller state, response payloads, and operator output in one place.',
    'settings.diagnostics.inventory': 'Inventory Snapshot',
    'settings.diagnostics.output': 'Output Log',
    'settings.diagnostics.field': 'Field',
    'settings.diagnostics.format': 'Format',
    'settings.diagnostics.value': 'Value',
    'settings.diagnostics.time': 'Time',
    'settings.diagnostics.data': 'Data',
    'settings.diagnostics.idle': 'System idle. Initialize hardware to view live parameters...',
    'settings.diagnostics.offline': 'System offline. Initialize hardware to view live parameters...',
    'settings.diagnostics.errorLoading': 'Error loading status',
    'settings.buttons.initializeHardware': 'Initialize Hardware',
    'settings.buttons.disconnect': 'Disconnect',
    'settings.buttons.startSimulator': 'Start Simulator',
    'settings.buttons.stopSimulator': 'Stop Simulator',
    'settings.buttons.wipeMemory': 'Wipe Branson Memory (CLR)',
    'serial.noPorts': 'No serial ports found',
    'serial.detecting': 'Detecting...',
    'status.online': 'ONLINE',
    'status.offline': 'OFFLINE',
    'status.partial': 'PARTIAL',
    'status.simOnline': 'SIM ONLINE',
    'connectionFailurePopup.eyebrow': 'Connection Failed',
    'connectionFailurePopup.title': 'Hardware Connection Incomplete',
    'connectionFailurePopup.messageFallback': 'The hardware connection did not complete. Check Ethernet and Teensy, then retry.',
    'connectionFailurePopup.reconnect': 'Reconnect',
    'connectionFailurePopup.dismiss': 'Dismiss',
    'connectionPopup.eyebrow': 'Warning',
    'connectionPopup.title': 'Confirm Mode Switch',
    'connectionPopup.confirm': 'Yes',
    'connectionPopup.cancel': 'Cancel',
    'connectionPopup.message.toSimulation': 'Are you sure you want to switch to simulation mode? If you press yes, the system will disconnect from the generator.',
    'connectionPopup.message.toNormal': 'Are you sure you want to switch to hardware mode? If you press yes, the system will disconnect from the simulator.'
  },
  fr: {
    'header.workspace': 'Espace de travail',
    'views.dashboard': 'Tableau de bord',
    'views.tests': 'Essais',
    'views.method': 'Methode',
    'views.sequencer': 'Sequence',
    'views.workflow': 'Workflow',
    'views.settings': 'Parametres',
    'footer.systemReady': 'SYSTEME PRET',
    'footer.simulatorReady': 'SIMULATEUR PRET',
    'footer.connectionDegraded': 'VERIFIEZ LES CONNEXIONS',
    'footer.waitingForConnection': 'EN ATTENTE DE CONNEXION',
    'footer.latency': 'Latence',
    'footer.build': 'Version',
    'sidebar.productSubtitle': 'Console industrielle de commande ultrasonique',
    'sidebar.nav.dashboard': 'Tableau de bord',
    'sidebar.nav.tests': 'Essais',
    'sidebar.nav.method': 'Methode',
    'sidebar.nav.settings': 'Parametres',
    'sidebar.simulation.title': 'Mode de fonctionnement',
    'sidebar.simulation.description': 'Choisissez le mode cible puis cliquez sur Demarrer ou Arreter.',
    'sidebar.simulation.hardware': 'Materiel',
    'sidebar.simulation.simulation': 'Simulation',
    'sidebar.simulation.start': 'Demarrer',
    'sidebar.simulation.stop': 'Arreter',
    'dashboard.realtime.title': 'Donnees en temps reel',
    'dashboard.realtime.description': 'Mesures actuelles provenant de la pile DCX.',
    'dashboard.labels.frequency': 'Frequence',
    'dashboard.labels.amplitude': 'Amplitude',
    'dashboard.labels.cycles': 'Cycles',
    'dashboard.indicators.ready': 'Pret',
    'dashboard.indicators.sonics': 'Ultrasons',
    'dashboard.indicators.alarm': 'Alarme',
    'dashboard.indicators.seeking': 'Recherche',
    'dashboard.manual.title': 'Commande manuelle',
    'dashboard.manual.description': 'Commandes operateur directes pour demarrer, arreter, accorder et reinitialiser.',
    'dashboard.manual.amplitudeTarget': 'Cible amplitude (%)',
    'dashboard.manual.start': 'Demarrer',
    'dashboard.manual.stop': 'Arreter',
    'dashboard.manual.seek': 'Recherche',
    'dashboard.manual.reset': 'Reset',
    'dashboard.graph.title': 'Graphe de telemetrie',
    'dashboard.graph.description': 'Trace la telemetrie en direct chaque fois que le controleur est en ligne, y compris au repos.',
    'dashboard.graph.xAxis': 'Axe X',
    'dashboard.graph.yAxis': 'Axe Y',
    'dashboard.graph.play': 'Lecture',
    'dashboard.graph.pause': 'Pause',
    'dashboard.graph.clear': 'Effacer',
    'chart.axis.time': 'Temps',
    'chart.axis.frequency': 'Frequence',
    'chart.axis.amplitude': 'Amplitude',
    'chart.axis.power': 'Puissance',
    'chart.axis.cycles': 'Cycles',
    'sequencer.library.title': 'Bibliotheque de sequences',
    'sequencer.library.description': 'Les routines enregistrees peuvent etre consultees et chargees ici.',
    'sequencer.library.empty': 'Les sequences enregistrees apparaitront ici.',
    'sequencer.sequenceName': 'Nom de la sequence',
    'sequencer.buttons.saveChanges': 'Enregistrer les modifications',
    'sequencer.buttons.saveSequence': 'Enregistrer la sequence',
    'sequencer.buttons.createSequence': 'Creer une sequence',
    'sequencer.buttons.execute': 'Executer la sequence',
    'sequencer.buttons.stop': 'Arreter la sequence',
    'sequencer.buttons.wipeAll': 'Tout effacer',
    'sequencer.blocks.pulse': 'Impulsion',
    'sequencer.blocks.pause': 'Arret',
    'sequencer.construction.title': 'Construction de sequence',
    'sequencer.construction.description': 'Organisez des blocs d impulsion et d arret puis executez la timeline.',
    'sequencer.timeline.label': 'Timeline (glisser les blocs pour reordonner)',
    'sequencer.config.title': 'Configuration de la routine active',
    'sequencer.config.description': 'Parametres globaux qui pilotent l execution de la timeline courante.',
    'sequencer.config.globalRamp': 'Rampe globale (ms)',
    'sequencer.config.autoAbort': 'Arret automatique',
    'sequencer.config.loopCount': 'Nombre de boucles',
    'sequencer.config.onAlarm': 'Sur alarme',
    'sequencer.config.never': 'Jamais',
    'sequencer.actions.load': 'Charger',
    'sequencer.actions.duplicate': 'Dupliquer',
    'sequencer.actions.delete': 'Supprimer',
    'sequencer.blocks.single': 'bloc',
    'sequencer.blocks.plural': 'blocs',
    'sequencer.confirmDelete': 'Supprimer la sequence enregistree "{name}" ?',
    'sequencer.saveState.draft': 'Nouveau brouillon non enregistre',
    'sequencer.saveState.dirty': 'Modifications non enregistrees',
    'sequencer.saveState.savingNew': 'Creation de la sequence...',
    'sequencer.saveState.savingChanges': 'Enregistrement des modifications...',
    'sequencer.saveState.saved': 'Toutes les modifications sont enregistrees',
    'sequencer.saveState.nameRequired': 'Saisissez un nom avant d enregistrer',
    'sequencer.saveState.duplicateName': 'Une sequence avec ce nom existe deja',
    'sequencer.saveState.empty': 'Ajoutez au moins un bloc avant d enregistrer',
    'sequencer.saveState.loadBeforeSave': 'Chargez une sequence enregistree avant de sauvegarder les modifications',
    'sequencer.saveState.autoSaveFailed': 'Echec de l enregistrement automatique',
    'sequencer.copySuffix': 'Copie',
    'sequencer.progress.idle': 'INACTIF',
    'workflow.title': 'Workflow de script avance',
    'workflow.description': 'Validez et executez des scripts de commandes de plus haut niveau sur le controleur.',
    'workflow.placeholder': '// Exemple:\nSET_AMP 80\nWAIT 1000\nSTART\nWAIT 5000\nSTOP',
    'workflow.library.title': 'Bibliotheque de workflows',
    'workflow.library.description': 'Enregistrez des scripts reutilisables pour les taches operateur repetitives.',
    'workflow.library.name': 'Nom du workflow',
    'workflow.library.namePlaceholder': 'Routine d inspection...',
    'workflow.library.save': 'Enregistrer dans la bibliotheque',
    'workflow.library.load': 'Charger',
    'workflow.library.delete': 'Supprimer',
    'workflow.library.empty': 'Les workflows enregistres apparaitront ici.',
    'workflow.library.ready': 'Bibliotheque prete',
    'workflow.library.saved': 'Workflow enregistre dans la bibliotheque',
    'workflow.library.updated': 'Workflow mis a jour dans la bibliotheque',
    'workflow.library.loaded': 'Workflow charge depuis la bibliotheque',
    'workflow.library.deleted': 'Workflow supprime de la bibliotheque',
    'workflow.library.exampleLoaded': 'Exemple charge dans l editeur',
    'workflow.library.errorLoad': 'Impossible de charger les workflows enregistres',
    'workflow.library.errorNameRequired': 'Saisissez un nom de workflow avant l enregistrement',
    'workflow.library.errorScriptRequired': 'Saisissez un script de workflow avant l enregistrement',
    'workflow.library.errorDuplicate': 'Un workflow avec ce nom existe deja',
    'workflow.library.confirmDelete': 'Supprimer le workflow enregistre "{name}" ?',
    'workflow.library.lineSingle': 'ligne',
    'workflow.library.linePlural': 'lignes',
    'workflow.help.title': 'Aide syntaxique et exemples',
    'workflow.help.description': 'Utilisez ces commandes prises en charge et ces exemples pour creer un script valide.',
    'workflow.help.commands': 'Commandes prises en charge',
    'workflow.help.start': 'Demarre les ultrasons, avec amplitude optionnelle.',
    'workflow.help.stop': 'Arrete immediatement les ultrasons.',
    'workflow.help.setAmp': 'Definit la cible d amplitude de soudure.',
    'workflow.help.wait': 'Met l execution en pause pendant une duree en millisecondes.',
    'workflow.help.seek': 'Lance un cycle de recherche.',
    'workflow.help.reset': 'Efface les alarmes actives.',
    'workflow.help.examples': 'Scripts exemples',
    'workflow.example.ramp': 'Verification de rampe',
    'workflow.example.seek': 'Verification de recherche',
    'workflow.example.pulse': 'Train d impulsions',
    'tests.title': 'Essais disponibles',
    'tests.description': 'Filtrez les essais de sequence et de workflow enregistres puis chargez-en un pour comparaison.',
    'tests.filters.search': 'Recherche',
    'tests.filters.searchPlaceholder': 'Rechercher des essais...',
    'tests.filters.sort': 'Trier par',
    'tests.filters.sort.date': 'Date',
    'tests.filters.sort.name': 'Nom',
    'tests.filters.sort.blocks': 'Blocs',
    'tests.filters.updatedAt': 'Mis a jour',
    'tests.list.title': 'Essais correspondants',
    'tests.list.empty': 'Aucun essai enregistre trouve.',
    'tests.actions.load': 'Charger l essai',
    'tests.actions.run': 'Executer',
    'tests.type.sequence': 'Sequence',
    'tests.type.workflow': 'Workflow',
    'tests.graph.title': 'Graphe de comparaison des essais',
    'tests.graph.description': 'Chargez un essai enregistre pour tracer son profil ideal puis executez-le pour superposer les donnees mesurees ou simulees.',
    'tests.graph.loaded': 'Essai charge',
    'tests.graph.noneLoaded': 'Aucun essai charge',
    'tests.graph.noneLoadedDescription': 'Chargez un essai de sequence ou de workflow enregistre pour comparer les traces ideales et reelles.',
    'tests.graph.runLoaded': 'Executer l essai charge',
    'tests.graph.ideal': 'Ideal',
    'tests.graph.measured': 'Mesure',
    'tests.graph.simulated': 'Simule',
    'tests.sequences.title': 'Essais de sequence',
    'tests.sequences.description': 'Parcourez les essais de sequence enregistres et chargez-en un dans Methode.',
    'tests.workflows.title': 'Essais de workflow',
    'tests.workflows.description': 'Parcourez les essais de workflow enregistres et chargez-en un dans Methode.',
    'method.title': 'Constructeur de methode',
    'method.description': 'Creez et executez des methodes de sequence ou de workflow depuis un seul espace.',
    'method.home.new': 'Creer',
    'method.home.blank': 'Vide',
    'method.home.example': 'Exemple',
    'method.home.exampleDescription': 'Partez d un modele de script verifie.',
    'method.home.newSequence': 'Nouvelle sequence',
    'method.home.newSequenceDescription': 'Commencez avec une timeline d impulsions vide.',
    'method.home.newWorkflow': 'Nouveau workflow',
    'method.home.newWorkflowDescription': 'Ouvrez un espace de script vierge.',
    'method.home.recents': 'Recents',
    'method.home.all': 'Tous',
    'method.home.favorites': 'Favoris',
    'method.home.sequence': 'Sequence',
    'method.home.workflow': 'Workflow',
    'method.home.searchPlaceholder': 'Rechercher des methodes',
    'method.home.empty': 'Aucune methode ne correspond encore a cette vue.',
    'method.home.favorite': 'Favori',
    'method.home.unfavorite': 'Favori',
    'method.home.duplicate': 'Dupliquer',
    'method.home.delete': 'Supprimer',
    'method.home.updated': 'Mis a jour',
    'method.navigation.home': 'Accueil methode',
    'method.sequence.title': 'Methode de sequence',
    'method.sequence.description': 'Nommez, enregistrez et preparez une methode d essai basee sur une sequence.',
    'method.workflow.title': 'Methode de workflow',
    'method.workflow.description': 'Enregistrez, chargez des fichiers et executez une methode d essai basee sur un workflow.',
    'sequencer.editor.title': 'Editeur de sequence',
    'sequencer.editor.description': 'Construisez, enregistrez et executez des methodes de sequence dans un editeur cible.',
    'sequencer.preview.title': 'Apercu de sequence',
    'sequencer.preview.description': 'Visualisez le profil d amplitude prevu avant d executer la sequence.',
    'sequencer.preview.dataset': 'Apercu de sequence',
    'sequencer.preview.loopSingle': 'boucle',
    'sequencer.preview.loopPlural': 'boucles',
    'workflow.editor.title': 'Editeur de workflow',
    'workflow.editor.description': 'Redigez, validez et enregistrez des methodes de workflow dans un editeur cible.',
    'workflow.statusLabel': 'Statut du workflow',
    'workflow.status.idle': 'INACTIF',
    'workflow.status.preparing': 'PREPARATION',
    'workflow.status.stopping': 'ARRET',
    'workflow.status.completed': 'TERMINE',
    'workflow.status.stopped': 'ARRETE',
    'workflow.status.error': 'ERREUR',
    'workflow.status.line': 'LIGNE {current}/{total} · {command}',
    'workflow.file.none': 'Aucun script charge',
    'workflow.file.loaded': 'Charge : {name}',
    'workflow.run': 'Valider et executer',
    'workflow.stop': 'Arreter le workflow',
    'workflow.load': 'Charger le script...',
    'workflow.save': 'Enregistrer le script...',
    'settings.connection.title': 'Parametres de connexion',
    'settings.connection.description': 'Choisissez la couche de transport et initialisez ou liberez l appareil.',
    'settings.interfaceMode': 'Mode interface',
    'settings.interface.http': 'HTTP direct (Branson DCX)',
    'settings.interface.serial': 'Pont serie Teensy 4.1',
    'settings.targetIp': 'Adresse IP cible',
    'settings.communicationPort': 'Port de communication',
    'settings.description': 'Organisez les preferences systeme, le routage et le suivi E/S, les graphes de signature, l historique des alarmes et la documentation dans un seul espace.',
    'settings.tabs.system': 'Systeme',
    'settings.tabs.setup': 'Reglages',
    'settings.tabs.io': 'Configuration E/S',
    'settings.tabs.signature': 'Signature recherche et sonotrode',
    'settings.tabs.alarms': 'Journal des alarmes',
    'settings.tabs.docs': 'Aide et doc',
    'settings.setup.title': 'Reglages generateur',
    'settings.setup.description': 'Ajustez les valeurs par defaut amplitude, frequence, seek et mise sous tension dans un seul espace.',
    'settings.setup.sections.amplitude': 'Amplitude',
    'settings.setup.sections.frequency': 'Frequence',
    'settings.setup.sections.misc': 'CONFIG DIVERSE',
    'settings.setup.sections.seek': 'SEEK',
    'settings.setup.sections.powerOn': 'MISE SOUS TENSION',
    'settings.setup.amplitudeRamp': 'Rampe amplitude (ms)',
    'settings.setup.external': 'Externe',
    'settings.setup.digitalTune': 'Accord numerique (Hz)',
    'settings.setup.internalOffset': 'Offset interne (Hz)',
    'settings.setup.externalOffset': 'Offset externe',
    'settings.setup.endOfWeldStore': 'Memorisation fin de soudure',
    'settings.setup.clearMemoryWithReset': 'Effacer la memoire avec Reset',
    'settings.setup.clearMemoryBeforeSeek': 'Effacer la memoire avant Seek',
    'settings.setup.setWithHornScan': 'Definir avec scan sonotrode',
    'settings.setup.alarmsResetRequired': 'Alarmes - Reset requis',
    'settings.setup.seekRamp': 'Rampe seek (ms)',
    'settings.setup.seekTime': 'Temps seek (ms)',
    'settings.setup.frequencyOffset': 'Offset frequence (Hz)',
    'settings.setup.timedSeek': 'Seek temporise',
    'settings.setup.off': 'Off',
    'settings.setup.seek': 'Seek',
    'settings.setup.scan': 'Scan',
    'settings.setup.clearMemory': 'Effacer la memoire',
    'settings.setup.rangeIndicator': 'Plage : {min} a {max}',
    'settings.setup.save': 'Enregistrer',
    'settings.setup.cancel': 'Annuler',
    'settings.setup.restoreDefaults': 'Restaurer les valeurs par defaut',
    'settings.preferences.title': 'Preferences',
    'settings.preferences.description': 'Choisissez la langue de l application et le theme visuel.',
    'settings.system.title': 'Maintenance systeme',
    'settings.system.description': 'Executez des actions de maintenance cote operateur pour le controleur connecte.',
    'settings.systemInfo.title': 'Informations systeme',
    'settings.systemInfo.description': 'Consultez en un coup d oeil les informations d identification du controleur et de l alimentation.',
    'settings.systemInfo.systemPanel': 'Systeme',
    'settings.systemInfo.powerSupplyPanel': 'Alimentation',
    'settings.systemInfo.system': 'Systeme',
    'settings.systemInfo.display': 'Affichage',
    'settings.systemInfo.softwareVersion': 'Version logicielle',
    'settings.systemInfo.systemVersion': 'Version systeme',
    'settings.systemInfo.fpgaVersion': 'Version FPGA',
    'settings.systemInfo.dcxCrc': 'CRC DCX',
    'settings.systemInfo.systemCrc': 'CRC systeme',
    'settings.systemInfo.powerLevel': 'Niveau de puissance',
    'settings.systemInfo.frequency': 'Frequence',
    'settings.systemInfo.serialNumber': 'Numero de serie',
    'settings.systemInfo.lifetimeCycles': 'Cycles a vie',
    'settings.systemInfo.generalAlarms': 'Alarmes generales',
    'settings.systemInfo.hoursOfSonics': 'Heures d ultrasons',
    'settings.systemInfo.powerOnHours': 'Heures sous tension',
    'settings.systemInfo.specPassword': 'Mot de passe spec.',
    'settings.systemInfo.specPasswordEnabled': 'Mot de passe spec. actif',
    'settings.docs.title': 'Aide et documentation',
    'settings.docs.description': 'Reference operationnelle structuree pour la connexion, le controle, les methodes et les limites de mise en service.',
    'settings.docs.referenceEyebrow': 'Reference operateur',
    'settings.docs.referenceTitle': 'Reference d exploitation DCX / Teensy',
    'settings.docs.referenceBody': 'Utilisez cette reference controlee pour l exploitation quotidienne, les verifications de mise en service et la formation.',
    'settings.docs.meta.docType': 'Type de document',
    'settings.docs.meta.docTypeValue': 'Guide operateur',
    'settings.docs.meta.controlPolicy': 'Politique de controle',
    'settings.docs.meta.controlPolicyValue': 'Ultrasons routes via Teensy',
    'settings.docs.meta.hardwareMode': 'Mode materiel',
    'settings.docs.meta.hardwareModeValue': 'HTTP Branson + Serie Teensy',
    'settings.docs.meta.simulationMode': 'Mode simulation',
    'settings.docs.meta.simulationModeValue': 'Modele logiciel interne',
    'settings.docs.notice.title': 'Avis securite et routage',
    'settings.docs.notice.description': 'Relisez ces regles de chemin de commande avant d exploiter le materiel.',
    'settings.docs.notice.hardwareTitle': 'Mode materiel',
    'settings.docs.notice.hardwareBody': 'Le mode materiel initialise ensemble le controleur Branson et l interface Teensy avant exploitation.',
    'settings.docs.notice.sonicsTitle': 'Commande ultrasons',
    'settings.docs.notice.sonicsBody': 'Les ordres Start et Stop ultrasons sont volontairement emis uniquement via les commandes Teensy START et STOP.',
    'settings.docs.notice.bransonTitle': 'Fonctions Branson',
    'settings.docs.notice.bransonBody': 'La lecture de statut, le seek, le reset et les ecritures de parametres restent sur le chemin HTTP Branson.',
    'settings.docs.start.title': 'Procedure operationnelle standard',
    'settings.docs.start.description': 'Suivez cette procedure standard avant tout run manuel ou automatise.',
    'settings.docs.start.connectTitle': 'Connexion',
    'settings.docs.start.connectBody': 'Selectionnez Materiel ou Simulation. En mode materiel, l application se connecte au controleur Branson et a l interface Teensy avant exploitation.',
    'settings.docs.start.statusTitle': 'Verifier le statut',
    'settings.docs.start.statusBody': 'Ouvrez le Dashboard pour confirmer les valeurs live, les indicateurs et l etat de connexion avant de lancer quoi que ce soit.',
    'settings.docs.start.manualTitle': 'Pilotage manuel',
    'settings.docs.start.manualBody': 'Utilisez Start, Stop, Seek, Reset et la cible amplitude pour un controle manuel rapide.',
    'settings.docs.start.methodsTitle': 'Utiliser les methodes',
    'settings.docs.start.methodsBody': 'Passez a Sequence ou Workflow lorsque vous voulez des routines d essai repetables plutot que des actions manuelles ponctuelles.',
    'settings.docs.manual.title': 'Commandes manuelles',
    'settings.docs.manual.description': 'Ce sont les controles les plus rapides pour les actions operateur directes.',
    'settings.docs.manual.amplitudeTitle': 'Cible amplitude',
    'settings.docs.manual.amplitudeBody': 'Reglez la cible amplitude avant d appuyer sur Start afin que le prochain weld commence au niveau attendu.',
    'settings.docs.manual.startStopTitle': 'Start / Stop',
    'settings.docs.manual.startStopBody': 'Utilisez Start et Stop uniquement en mode materiel. L application envoie START et STOP a l interface Teensy.',
    'settings.docs.manual.seekTitle': 'Seek',
    'settings.docs.manual.seekBody': 'Utilisez Seek pour lancer un cycle d accord ou commencer un scan de signature sonotrode.',
    'settings.docs.manual.resetTitle': 'Reset',
    'settings.docs.manual.resetBody': 'Utilisez Reset apres une alarme ou une surcharge pour effacer l etat du controleur avant de relancer.',
    'settings.docs.signature.title': 'Reference acquisition signatures',
    'settings.docs.signature.description': 'Selectionnez le mode d acquisition adapte, relisez les traces capturees et exportez le jeu de donnees si necessaire.',
    'settings.docs.signature.weldTitle': 'Graphe donnees soudure',
    'settings.docs.signature.weldBody': 'Utilisez ce mode pour capturer 5 secondes de donnees de soudure, choisir les traces a afficher et exporter le resultat si besoin.',
    'settings.docs.signature.hornTitle': 'Graphe signature sonotrode',
    'settings.docs.signature.hornBody': 'Utilisez ce mode pendant Seek pour comparer le comportement de resonance de la sonotrode et exporter le scan a la fin.',
    'settings.docs.methods.title': 'Sequences et workflows',
    'settings.docs.methods.description': 'Utilisez ces outils lorsque vous avez besoin de runs repetables en plusieurs etapes plutot que d actions manuelles rapides.',
    'settings.docs.methods.sequenceTitle': 'Sequence',
    'settings.docs.methods.sequenceBody': 'Utilisez la vue Sequence pour construire des blocs pulses et pauses avec amplitudes et ramps configurables.',
    'settings.docs.methods.workflowTitle': 'Workflow',
    'settings.docs.methods.workflowBody': 'Utilisez la vue Workflow pour des procedures pas a pas qui combinent start, stop, seek, reset, attentes et changements d amplitude.',
    'settings.docs.methods.reviewTitle': 'Relecture',
    'settings.docs.methods.reviewBody': 'Utilisez Journal des alarmes et Sortie systeme dans Settings pour revoir ce qui s est passe pendant un run.',
    'settings.docs.limits.title': 'Limites connues et notes de mise en service',
    'settings.docs.limits.description': 'Ces notes expliquent pourquoi une fonction peut apparaitre dans l interface sans etre encore totalement disponible.',
    'settings.docs.limits.clearMemory': 'Le bouton d effacement memoire est visible mais n est pas encore disponible.',
    'settings.docs.limits.systemMetadata': 'Les informations systeme dependent du firmware controleur ; un champ vide signifie qu aucune valeur n a ete renvoyee.',
    'settings.docs.limits.advancedTelemetry': 'Certaines traces avancees de signature peuvent rester vides tant que le controleur ne fournit pas ces mesures.',
    'settings.docs.columns.function': 'Fonction',
    'settings.docs.columns.mapping': 'Mapping',
    'settings.docs.columns.usedBy': 'Utilise par',
    'settings.docs.columns.command': 'Commande',
    'settings.docs.columns.detail': 'Detail',
    'settings.docs.transports.title': 'Architecture de transport',
    'settings.docs.transports.description': 'Le mode materiel combine le controle HTTP Branson avec des commandes ultrasons gerees par Teensy ; la simulation garde l interface active sans materiel.',
    'settings.docs.transports.httpTitle': 'HTTP Branson',
    'settings.docs.transports.httpBody': 'Prend en charge la lecture de statut, le seek, le reset et les ecritures de parametres via les endpoints Branson fonction/cmd.',
    'settings.docs.transports.serialTitle': 'Serie Teensy',
    'settings.docs.transports.serialBody': 'Prend en charge les commandes d activation ultrasons en mode materiel en envoyant START et STOP au Teensy.',
    'settings.docs.transports.simTitle': 'Simulation',
    'settings.docs.transports.simBody': 'Simule la telemetrie et les changements d etat pour valider l interface en securite sans materiel actif.',
    'settings.docs.workflow.title': 'Reference commandes workflow',
    'settings.docs.workflow.description': 'Ces operations de workflow et de sequence sont deja traduites en actions controleur.',
    'settings.docs.workflow.start': 'Demarre les ultrasons avec une amplitude optionnelle.',
    'settings.docs.workflow.stop': 'Arrete immediatement les ultrasons.',
    'settings.docs.workflow.setAmp': 'Met a jour l amplitude de soudure avant le prochain weld.',
    'settings.docs.workflow.seek': 'Lance un cycle de recherche / scan sonotrode.',
    'settings.docs.workflow.reset': 'Efface les alarmes actives.',
    'settings.docs.workflow.wait': 'Met l execution en pause pendant une duree en millisecondes.',
    'settings.docs.functions.title': 'Cartographie interface de controle',
    'settings.docs.functions.description': 'Ces actions de controle sont deja accessibles depuis l interface actuelle, le moteur de sequence ou le moteur de workflow.',
    'settings.docs.functions.statusRead': 'Lecture statut',
    'settings.docs.functions.startSonics': 'Demarrage ultrasons',
    'settings.docs.functions.stopSonics': 'Arret ultrasons',
    'settings.docs.functions.seek': 'Recherche',
    'settings.docs.functions.alarmReset': 'Reset alarme',
    'settings.docs.functions.setAmplitude': 'Reglage amplitude',
    'settings.docs.usage.statusRead': 'Heartbeat, dashboard, diagnostics',
    'settings.docs.usage.startSonics': 'Demarrage dashboard, sequences, workflows',
    'settings.docs.usage.stopSonics': 'Arret dashboard, sequences, workflows',
    'settings.docs.usage.seek': 'Recherche dashboard, signature sonotrode, workflows',
    'settings.docs.usage.alarmReset': 'Reset dashboard, reset surcharge, workflows',
    'settings.docs.usage.setAmplitude': 'Cible depart manuelle, sequences, workflows',
    'settings.docs.mapping.statusRead': 'Lit l etat live du controleur, la telemetrie et les metadonnees disponibles.',
    'settings.docs.mapping.startSonics': 'Applique d abord la cible amplitude sur Branson puis emet START vers le Teensy.',
    'settings.docs.mapping.stopSonics': 'Emet STOP vers le Teensy pour arreter les ultrasons en mode materiel.',
    'settings.docs.mapping.seek': 'Lance le cycle seek gere par le controleur depuis l interface Branson.',
    'settings.docs.mapping.alarmReset': 'Efface les alarmes et l etat de surcharge du controleur via l interface Branson.',
    'settings.docs.mapping.setAmplitude': 'Ecrit les parametres amplitude sur Branson avant le prochain weld ou la prochaine etape script.',
    'settings.docs.parameters.title': 'Ecritures parametres prises en charge',
    'settings.docs.parameters.description': 'Ces cles de parametres controleur sont deja acceptees par le chemin de mise a jour des parametres.',
    'settings.docs.gaps.title': 'Ecarts connus',
    'settings.docs.gaps.description': 'Ces zones demandent encore un travail cote controleur ou cote application.',
    'settings.docs.gaps.clearMemory': 'Commande CLR / effacement memoire',
    'settings.docs.gaps.systemMetadata': 'Lecture des metadonnees systeme (version LCD, CRC, numero de serie)',
    'settings.docs.gaps.advancedTelemetry': 'Telemetrie live phase/courant/amplitude PWM depuis le controleur',
    'settings.io.title': 'Configuration E/S',
    'settings.io.description': 'Gardez les commandes de routage et les E/S numeriques et analogiques en direct dans une seule vue.',
    'settings.io.digitalInputs': 'Entrees numeriques',
    'settings.io.digitalOutputs': 'Sorties numeriques',
    'settings.io.analogInputs': 'Entrees analogiques',
    'settings.io.analogOutputs': 'Sorties analogiques',
    'settings.io.externalStart': 'Demarrage externe',
    'settings.io.externalSeek': 'Recherche externe',
    'settings.io.externalReset': 'Reset externe',
    'settings.io.memoryClear': 'Effacement memoire',
    'settings.io.ready': 'Pret',
    'settings.io.sonicsActive': 'Ultrasons actifs',
    'settings.io.generalAlarm': 'Alarme generale',
    'settings.io.seekScanOut': 'Sortie recherche/scan',
    'settings.io.amplitudeIn': 'Amplitude entrante (V)',
    'settings.io.frequencyOffset': 'Offset frequence (V)',
    'settings.io.powerOut': 'Puissance sortie (V)',
    'settings.io.amplitudeOut': 'Amplitude sortie (V)',
    'settings.language': 'Langue',
    'settings.language.english': 'Anglais',
    'settings.language.french': 'Francais',
    'settings.theme': 'Mode de theme',
    'settings.theme.dark': 'Sombre',
    'settings.theme.light': 'Clair',
    'settings.theme.system': 'Systeme',
    'settings.routing.title': 'Routage des commandes',
    'settings.routing.description': 'Deleguez chaque famille de commandes a Ethernet, au serie ou au mode principal.',
    'settings.routing.followMainMode': 'Suivre le mode principal',
    'settings.routing.ethernet': 'Ethernet (DCX)',
    'settings.routing.serial': 'Teensy (Serie)',
    'settings.routing.sonics': '(Demarrer/Arreter)',
    'settings.routing.amplitude': 'Controle amplitude',
    'settings.routing.seek': 'Recherche / Accord',
    'settings.routing.reset': 'Reset alarme',
    'settings.signature.title': 'Graphe de signature recherche et sonotrode',
    'settings.signature.description': 'Basculez entre le chargement du graphe de soudure memorise et un scan de signature de sonotrode dans un seul espace.',
    'settings.signature.clear': 'Effacer le graphe',
    'settings.signature.weldDataGraph': 'Graphe donnees soudure',
    'settings.signature.hornSignatureGraph': 'Graphe signature sonotrode',
    'settings.signature.weldDataDescription': 'Chargez le graphe de soudure memorise depuis le DCX via Ethernet puis affichez ou exportez les parametres selectionnes.',
    'settings.signature.hornSignatureDescription': 'Diagnostiquez la resonance de la sonotrode avec des traces de phase, courant et amplitude affichables ou exportables.',
    'settings.signature.startWeldCapture': 'Charger graphe soudure',
    'settings.signature.startHornScan': 'Demarrer scan sonotrode',
    'settings.signature.startTest': 'Demarrer le test',
    'settings.signature.resetOverload': 'Reset surcharge',
    'settings.signature.abortHornScan': 'Annuler scan sonotrode',
    'settings.signature.status': 'Statut',
    'settings.signature.result': 'Resultat',
    'settings.signature.passed': 'Reussi',
    'settings.signature.failed': 'Echoue',
    'settings.signature.aborted': 'Annule',
    'settings.signature.scanIdle': 'Inactif',
    'settings.signature.scanRunning': 'Scan sonotrode en cours',
    'settings.signature.scanAborting': 'Annulation du scan sonotrode',
    'settings.signature.scanPassed': 'Scan sonotrode termine',
    'settings.signature.scanFailed': 'Echec du scan sonotrode',
    'settings.signature.scanAborted': 'Scan sonotrode annule',
    'settings.signature.run': 'Run',
    'settings.signature.frequency': 'Frequence',
    'settings.signature.memory': 'Memoire',
    'settings.signature.amplitude': 'Amplitude',
    'settings.signature.power': 'Puissance',
    'settings.signature.seek': 'Recherche',
    'settings.signature.phase': 'Phase',
    'settings.signature.current': 'Courant',
    'settings.signature.pwmAmplitude': 'Amplitude PWM',
    'settings.signature.alarm': 'Alarme',
    'settings.signature.okStored': 'OK-Memoire stockee',
    'settings.signature.overloadCleared': 'Surcharge-effacee',
    'settings.signature.updateGraph': 'Mettre a jour le graphe',
    'settings.signature.exportGraph': 'Exporter les donnees du graphe',
    'settings.signature.drawFrom': 'Tracer depuis (ms)',
    'settings.signature.drawFromHz': 'Tracer depuis (Hz)',
    'settings.signature.drawTo': 'Jusqu a (ms)',
    'settings.signature.drawToHz': 'Jusqu a (Hz)',
    'settings.signature.graphSelection': 'Selection graphe',
    'settings.signature.xValue': 'Valeur X',
    'settings.signature.xValueFrequency': 'Frequence (Hz)',
    'settings.signature.yValue': 'Valeur Y',
    'settings.signature.setDefault': 'Valeur par defaut',
    'settings.signature.updateValue': 'Mettre a jour la valeur',
    'settings.signature.percentScale': 'Amplitude / Puissance (%)',
    'settings.signature.amplitudeScale': 'Amplitude (%)',
    'settings.signature.phaseScale': 'Phase (deg)',
    'settings.signature.currentScale': 'Courant',
    'settings.signature.seekActive': 'ACTIVE',
    'settings.signature.seekIdle': 'INACTIVE',
    'settings.signature.dataset.frequency': 'Frequence',
    'settings.signature.dataset.power': 'Puissance',
    'settings.signature.dataset.amplitude': 'Amplitude',
    'settings.signature.dataset.phase': 'Phase',
    'settings.signature.dataset.current': 'Courant',
    'settings.signature.dataset.pwmAmplitude': 'Amplitude PWM',
    'settings.signature.weldGraphSetup': 'Parametres graphe soudure',
    'settings.signature.weldPresetData': 'Donnees preset soudure',
    'settings.signature.loadedPresetValues': 'Valeurs preset chargees',
    'settings.signature.noPresetData': 'Aucune donnee preset chargee.',
    'settings.signature.scanSetup': 'Parametres scan sonotrode',
    'settings.signature.resonance': 'Resonance',
    'settings.signature.frequencyStart': 'Frequence depart (Hz)',
    'settings.signature.frequencyStop': 'Frequence fin (Hz)',
    'settings.signature.frequencyStep': 'Pas de frequence (Hz)',
    'settings.signature.stepDelay': 'Delai par pas (ms)',
    'settings.signature.scanAmplitude': 'Amplitude (%)',
    'settings.signature.scanCurrent': 'Courant (%)',
    'settings.signature.seriesResonantPoint1': 'Point resonant serie 1 (Hz)',
    'settings.signature.parallelResonantPoint1': 'Point resonant parallele 1 (Hz)',
    'settings.alarms.title': 'Journal des alarmes',
    'settings.alarms.description': 'Suivez les transitions d alarmes detectees depuis la telemetrie temps reel.',
    'settings.alarms.time': 'Heure',
    'settings.alarms.state': 'Etat',
    'settings.alarms.detail': 'Detail',
    'settings.alarms.empty': 'Aucun evenement d alarme enregistre pour le moment.',
    'settings.alarms.active': 'ACTIVE',
    'settings.alarms.cleared': 'EFFACEE',
    'settings.output.title': 'Sortie systeme',
    'settings.output.description': 'Consultez les entrees brutes de l operateur et du controleur.',
    'settings.diagnostics.title': 'Diagnostics et journaux',
    'settings.diagnostics.description': 'Surveillez l etat du controleur, les reponses et la sortie operateur au meme endroit.',
    'settings.diagnostics.inventory': 'Instantane inventaire',
    'settings.diagnostics.output': 'Journal de sortie',
    'settings.diagnostics.field': 'Champ',
    'settings.diagnostics.format': 'Format',
    'settings.diagnostics.value': 'Valeur',
    'settings.diagnostics.time': 'Heure',
    'settings.diagnostics.data': 'Donnees',
    'settings.diagnostics.idle': 'Systeme inactif. Initialisez le materiel pour voir les parametres en direct...',
    'settings.diagnostics.offline': 'Systeme hors ligne. Initialisez le materiel pour voir les parametres en direct...',
    'settings.diagnostics.errorLoading': 'Erreur lors du chargement du statut',
    'settings.buttons.initializeHardware': 'Initialiser le materiel',
    'settings.buttons.disconnect': 'Deconnecter',
    'settings.buttons.startSimulator': 'Demarrer le simulateur',
    'settings.buttons.stopSimulator': 'Arreter le simulateur',
    'settings.buttons.wipeMemory': 'Effacer la memoire Branson (CLR)',
    'serial.noPorts': 'Aucun port serie detecte',
    'serial.detecting': 'Detection...',
    'status.online': 'EN LIGNE',
    'status.offline': 'HORS LIGNE',
    'status.partial': 'PARTIEL',
    'status.simOnline': 'SIM EN LIGNE',
    'connectionFailurePopup.eyebrow': 'Connexion echouee',
    'connectionFailurePopup.title': 'Connexion materielle incomplete',
    'connectionFailurePopup.messageFallback': 'La connexion materielle n a pas abouti. Verifiez Ethernet et le Teensy, puis reessayez.',
    'connectionFailurePopup.reconnect': 'Reconnecter',
    'connectionFailurePopup.dismiss': 'Fermer',
    'connectionPopup.eyebrow': 'Avertissement',
    'connectionPopup.title': 'Confirmer le changement de mode',
    'connectionPopup.confirm': 'Oui',
    'connectionPopup.cancel': 'Annuler',
    'connectionPopup.message.toSimulation': 'Voulez-vous vraiment passer en mode simulation ? Si vous appuyez sur oui, le systeme se deconnectera du generateur.',
    'connectionPopup.message.toNormal': 'Voulez-vous vraiment passer en mode materiel ? Si vous appuyez sur oui, le systeme se deconnectera du simulateur.'
  }
};

let themeMediaQuery = null;
let themeMediaListener = null;

function normalizeLanguage(language) {
  return language === 'fr' ? 'fr' : 'en';
}

function normalizeThemeMode(themeMode) {
  return ['dark', 'light', 'system'].includes(themeMode) ? themeMode : 'dark';
}

function persistPreferences() {
  return window.api.store.set(STORE_KEY, {
    language: runtimeState.language,
    themeMode: runtimeState.themeMode
  });
}

export function t(key, fallback = '') {
  const language = normalizeLanguage(runtimeState.language);
  return translations[language]?.[key] || translations.en[key] || fallback || key;
}

export function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    element.textContent = t(element.dataset.i18n, element.textContent);
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
    element.setAttribute('placeholder', t(element.dataset.i18nPlaceholder, element.getAttribute('placeholder') || ''));
  });
}

function resolveTheme(themeMode) {
  if (themeMode !== 'system') {
    return themeMode;
  }

  if (typeof window.matchMedia !== 'function') {
    return 'dark';
  }

  return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
}

function bindSystemThemeListener() {
  if (typeof window.matchMedia !== 'function') {
    return;
  }

  if (!themeMediaQuery) {
    themeMediaQuery = window.matchMedia('(prefers-color-scheme: light)');
  }

  if (themeMediaListener) {
    themeMediaQuery.removeEventListener('change', themeMediaListener);
    themeMediaListener = null;
  }

  themeMediaListener = () => {
    if (runtimeState.themeMode === 'system') {
      document.documentElement.dataset.theme = resolveTheme('system');
    }
  };

  themeMediaQuery.addEventListener('change', themeMediaListener);
}

export async function setLanguage(language, { persist = true } = {}) {
  runtimeState.language = normalizeLanguage(language);
  applyTranslations();

  const languageSelect = $('ui-language');
  if (languageSelect) {
    languageSelect.value = runtimeState.language;
  }

  document.dispatchEvent(new CustomEvent('app:language-changed', {
    detail: { language: runtimeState.language }
  }));

  if (persist) {
    await persistPreferences();
  }
}

export async function setThemeMode(themeMode, { persist = true } = {}) {
  runtimeState.themeMode = normalizeThemeMode(themeMode);
  document.documentElement.dataset.theme = resolveTheme(runtimeState.themeMode);
  bindSystemThemeListener();

  const themeSelect = $('ui-theme-mode');
  if (themeSelect) {
    themeSelect.value = runtimeState.themeMode;
  }

  document.dispatchEvent(new CustomEvent('app:theme-changed', {
    detail: { themeMode: runtimeState.themeMode }
  }));

  if (persist) {
    await persistPreferences();
  }
}

export async function loadUiPreferences() {
  const stored = await window.api.store.get(STORE_KEY);
  const language = normalizeLanguage(stored?.language);
  const themeMode = normalizeThemeMode(stored?.themeMode);

  await setLanguage(language, { persist: false });
  await setThemeMode(themeMode, { persist: false });
}

export function initPreferenceControls() {
  const languageSelect = $('ui-language');
  if (languageSelect && languageSelect.dataset.bound !== 'true') {
    languageSelect.dataset.bound = 'true';
    languageSelect.addEventListener('change', async () => {
      await setLanguage(languageSelect.value);
    });
  }

  const themeSelect = $('ui-theme-mode');
  if (themeSelect && themeSelect.dataset.bound !== 'true') {
    themeSelect.dataset.bound = 'true';
    themeSelect.addEventListener('change', async () => {
      await setThemeMode(themeSelect.value);
    });
  }
}
